spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/microservice
    username: root
    password: 2002

  application:
    name: CONFIG-DEFAULT
eureka:
  instance:
    prefer-ip-address: false
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

