spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/microservice
    username: root
    password: 2002
  application:
    name: CONFIG-DEFAULT
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

